// ─────────────────────────────────────────────
// DUMMY DATA  — used when the backend is offline
// ─────────────────────────────────────────────

export const DUMMY_RESTAURANTS = [
  {
    id: '1',
    name: 'The Spice Garden',
    description: 'Authentic Sri Lankan rice & curry, devilled dishes and fresh kottu — made with locally sourced spices every day.',
    town: 'Galle',
    district: 'Galle',
    province: 'Southern',
    address: '14 Church Street, Galle Fort, Galle',
    phone: '+94 91 222 4567',
    website: 'https://spicegarden.lk',
    type: 'restaurant',
    price_range: 'budget',
    cuisine_types: ['Sri Lankan', 'Rice & Curry', 'Kottu'],
    cover_image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80',
    open_hours: 'Mon – Sun  7:00 AM – 10:00 PM',
    restaurant_ratings: [{ avg_rating: 4.7, review_count: 134 }],
    menu_url: null,
    menu_items: [
      { id: 'm1', category: 'Rice & Curry', name: 'Full Rice & Curry Plate', price: 350, description: 'Rice with 5 curries, papadum and pickle', is_available: true },
      { id: 'm2', category: 'Rice & Curry', name: 'Half Board Rice & Curry', price: 220, description: 'Rice with 3 curries', is_available: true },
      { id: 'm3', category: 'Kottu', name: 'Chicken Kottu', price: 420, description: 'Godamba roti chopped with chicken, egg and vegetables', is_available: true },
      { id: 'm4', category: 'Kottu', name: 'Cheese Kottu', price: 480, description: 'Godamba roti with cheese and egg', is_available: true },
      { id: 'm5', category: 'Kottu', name: 'Vegetable Kottu', price: 320, description: 'Godamba roti with seasonal vegetables', is_available: true },
      { id: 'm6', category: 'Devilled', name: 'Devilled Chicken', price: 550, description: 'Sri Lankan style spicy devilled chicken', is_available: true },
      { id: 'm7', category: 'Devilled', name: 'Devilled Prawn', price: 750, description: 'Fresh prawns in spicy devilled sauce', is_available: true },
      { id: 'm8', category: 'Devilled', name: 'Devilled Cuttlefish', price: 680, description: 'Devilled cuttlefish with capsicum and onion', is_available: true },
      { id: 'm9', category: 'Beverages', name: 'King Coconut', price: 120, description: 'Fresh king coconut water', is_available: true },
      { id: 'm10', category: 'Beverages', name: 'Lime Juice', price: 150, description: 'Fresh lime with soda or water', is_available: true },
    ],
  },
  {
    id: '2',
    name: 'Cinnamon Sky Rooftop',
    description: 'Upscale rooftop dining with panoramic Colombo views. Western and Asian fusion with an extensive cocktail menu.',
    town: 'Colombo 03',
    district: 'Colombo',
    province: 'Western',
    address: '58 Galle Road, Colombo 03',
    phone: '+94 11 456 7890',
    website: 'https://cinnamonsky.lk',
    type: 'restaurant',
    price_range: 'premium',
    cuisine_types: ['Fusion', 'Western', 'Cocktails'],
    cover_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    open_hours: 'Tue – Sun  12:00 PM – 11:30 PM',
    restaurant_ratings: [{ avg_rating: 4.5, review_count: 89 }],
    menu_url: null,
    menu_items: [
      { id: 'm11', category: 'Starters', name: 'Tuna Tataki', price: 1800, description: 'Seared yellowfin tuna, ponzu dressing, micro greens', is_available: true },
      { id: 'm12', category: 'Starters', name: 'Burrata Salad', price: 1600, description: 'Fresh burrata, heirloom tomatoes, basil oil', is_available: true },
      { id: 'm13', category: 'Mains', name: 'Wagyu Beef Tenderloin', price: 5500, description: '200g wagyu beef, truffle fries, red wine jus', is_available: true },
      { id: 'm14', category: 'Mains', name: 'Pan-Seared Barramundi', price: 3200, description: 'Barramundi fillet, miso butter, jasmine rice', is_available: true },
      { id: 'm15', category: 'Mains', name: 'Mushroom Risotto', price: 2400, description: 'Porcini and truffle risotto, parmesan crisp', is_available: true },
      { id: 'm16', category: 'Desserts', name: 'Chocolate Fondant', price: 1400, description: 'Warm dark chocolate fondant, vanilla ice cream', is_available: true },
      { id: 'm17', category: 'Cocktails', name: 'Colombo Sunset', price: 1200, description: 'Rum, mango, lime, ginger beer', is_available: true },
      { id: 'm18', category: 'Cocktails', name: 'Ceylon Mule', price: 1100, description: 'Arrack, lime, ginger beer, mint', is_available: true },
    ],
  },
  {
    id: '3',
    name: 'Lake View Bakery',
    description: 'Freshly baked bread, pastries and short eats beside Kandy Lake. A favourite breakfast and evening tea spot.',
    town: 'Kandy',
    district: 'Kandy',
    province: 'Central',
    address: '9 Sangamitta Mawatha, Kandy',
    phone: '+94 81 223 1122',
    website: null,
    type: 'food_shop',
    price_range: 'budget',
    cuisine_types: ['Bakery', 'Short Eats', 'Pastries'],
    cover_image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    open_hours: 'Mon – Sat  6:00 AM – 8:00 PM',
    restaurant_ratings: [{ avg_rating: 4.3, review_count: 61 }],
    menu_url: null,
    menu_items: [
      { id: 'm21', category: 'Bread', name: 'Pol Roti', price: 40, description: 'Coconut flatbread, freshly made', is_available: true },
      { id: 'm22', category: 'Bread', name: 'White Loaf', price: 180, description: 'Freshly baked white sandwich loaf', is_available: true },
      { id: 'm23', category: 'Short Eats', name: 'Egg Roll', price: 65, description: 'Flaky pastry roll with egg filling', is_available: true },
      { id: 'm24', category: 'Short Eats', name: 'Chicken Puff', price: 75, description: 'Puff pastry with spiced chicken', is_available: true },
      { id: 'm25', category: 'Short Eats', name: 'Patties', price: 70, description: 'Vegetable or beef filled patties', is_available: true },
      { id: 'm26', category: 'Pastries', name: 'Butter Croissant', price: 220, description: 'Laminated butter croissant', is_available: true },
      { id: 'm27', category: 'Pastries', name: 'Chocolate Eclair', price: 180, description: 'Choux pastry with chocolate glaze', is_available: true },
      { id: 'm28', category: 'Beverages', name: 'Milk Tea', price: 120, description: 'Ceylon tea with locally sourced milk', is_available: true },
      { id: 'm29', category: 'Beverages', name: 'Coffee', price: 150, description: 'Hot or iced coffee', is_available: true },
    ],
  },
  {
    id: '4',
    name: 'Hotel Sigiri Palace',
    description: 'Full-service hotel restaurant serving Sri Lankan, Indian and Chinese breakfast, lunch and dinner buffets.',
    town: 'Dambulla',
    district: 'Matale',
    province: 'Central',
    address: 'Inamaluwa, Sigiriya Road, Dambulla',
    phone: '+94 66 228 4000',
    website: 'https://sigiripalace.lk',
    type: 'hotel',
    price_range: 'mid',
    cuisine_types: ['Sri Lankan', 'Indian', 'Chinese', 'Buffet'],
    cover_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    open_hours: 'Daily  6:30 AM – 10:30 PM',
    restaurant_ratings: [{ avg_rating: 4.1, review_count: 203 }],
    menu_url: null,
    menu_items: [
      { id: 'm31', category: 'Breakfast Buffet', name: 'Full Breakfast Buffet', price: 1200, description: 'String hoppers, pittu, egg dishes, fruits, toast', is_available: true },
      { id: 'm32', category: 'Lunch Buffet', name: 'Lunch Buffet', price: 1800, description: '12-dish Sri Lankan buffet with desserts', is_available: true },
      { id: 'm33', category: 'Dinner Buffet', name: 'Dinner Buffet', price: 2200, description: 'Sri Lankan and Chinese dishes, live cooking station', is_available: true },
      { id: 'm34', category: 'A La Carte', name: 'Nasi Goreng', price: 950, description: 'Indonesian-style fried rice with chicken', is_available: true },
      { id: 'm35', category: 'A La Carte', name: 'Chicken Fried Rice', price: 880, description: 'Wok-tossed rice with chicken and vegetables', is_available: true },
      { id: 'm36', category: 'A La Carte', name: 'Fish Curry', price: 780, description: 'Sri Lankan fish curry with rice', is_available: true },
      { id: 'm37', category: 'Beverages', name: 'Fresh Juice', price: 350, description: 'Pineapple, watermelon or orange', is_available: true },
    ],
  },
  {
    id: '5',
    name: 'Surf & Turf Mirissa',
    description: 'Beachfront seafood shack serving grilled catch-of-the-day, prawn curry and chilled king coconuts.',
    town: 'Mirissa',
    district: 'Matara',
    province: 'Southern',
    address: 'Beach Road, Mirissa',
    phone: '+94 41 225 0033',
    website: null,
    type: 'restaurant',
    price_range: 'mid',
    cuisine_types: ['Seafood', 'Grills', 'Sri Lankan'],
    cover_image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    open_hours: 'Daily  11:00 AM – 10:00 PM',
    restaurant_ratings: [{ avg_rating: 4.6, review_count: 177 }],
    menu_url: null,
    menu_items: [
      { id: 'm41', category: 'Seafood Grills', name: 'Grilled Red Snapper', price: 1800, description: 'Whole fish grilled with garlic butter and herbs', is_available: true },
      { id: 'm42', category: 'Seafood Grills', name: 'Garlic Butter Prawns', price: 2200, description: '6 large prawns, garlic butter, lemon', is_available: true },
      { id: 'm43', category: 'Seafood Grills', name: 'Grilled Lobster', price: 3800, description: 'Half lobster grilled with herb butter', is_available: true },
      { id: 'm44', category: 'Curry', name: 'Prawn Curry', price: 1600, description: 'Fresh prawn curry with rice and coconut sambol', is_available: true },
      { id: 'm45', category: 'Curry', name: 'Crab Curry', price: 2400, description: 'Blue swimmer crab in rich coconut curry', is_available: true },
      { id: 'm46', category: 'Sides', name: 'Coconut Rice', price: 350, description: 'Rice cooked in coconut milk', is_available: true },
      { id: 'm47', category: 'Sides', name: 'Pol Sambol', price: 150, description: 'Freshly ground coconut sambol', is_available: true },
      { id: 'm48', category: 'Beverages', name: 'King Coconut', price: 150, description: 'Chilled king coconut water', is_available: true },
    ],
  },
  {
    id: '6',
    name: 'Jaffna Tamil Kitchen',
    description: 'Traditional Northern Tamil cuisine — crab curry, mutton rolls, parippu and fresh string hoppers made to order.',
    town: 'Jaffna',
    district: 'Jaffna',
    province: 'Northern',
    address: '22 Hospital Road, Jaffna',
    phone: '+94 21 222 3344',
    website: null,
    type: 'restaurant',
    price_range: 'budget',
    cuisine_types: ['Tamil', 'Sri Lankan', 'Seafood'],
    cover_image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    open_hours: 'Mon – Sat  8:00 AM – 9:00 PM',
    restaurant_ratings: [{ avg_rating: 4.8, review_count: 98 }],
    menu_url: null,
    menu_items: [
      { id: 'm51', category: 'Breakfast', name: 'String Hoppers & Dhal', price: 180, description: 'Fresh string hoppers with parippu and coconut sambol', is_available: true },
      { id: 'm52', category: 'Breakfast', name: 'Idli Sambar', price: 160, description: '3 idlies with sambar and chutneys', is_available: true },
      { id: 'm53', category: 'Mains', name: 'Jaffna Crab Curry', price: 1200, description: 'Blue swimmer crab in Jaffna-style curry with rice', is_available: true },
      { id: 'm54', category: 'Mains', name: 'Mutton Curry Plate', price: 650, description: 'Mutton curry with rice, dhal and pickle', is_available: true },
      { id: 'm55', category: 'Mains', name: 'Vegetarian Thali', price: 380, description: 'Rice, 4 vegetarian curries, pickle, papadum', is_available: true },
      { id: 'm56', category: 'Snacks', name: 'Mutton Roll', price: 120, description: 'Flaky pastry roll with spiced mutton filling', is_available: true },
      { id: 'm57', category: 'Snacks', name: 'Vadai', price: 35, description: 'Crispy lentil doughnut, chutney dipped', is_available: true },
      { id: 'm58', category: 'Beverages', name: 'Filter Coffee', price: 80, description: 'Strong South Indian filter coffee', is_available: true },
    ],
  },
  {
    id: '7',
    name: 'Ella Café & Co.',
    description: 'Cosy café in the hills serving Western breakfasts, avocado toast, smoothie bowls and specialty coffee.',
    town: 'Ella',
    district: 'Badulla',
    province: 'Uva',
    address: 'Main Street, Ella',
    phone: '+94 57 222 8800',
    website: 'https://ellacafe.lk',
    type: 'food_shop',
    price_range: 'mid',
    cuisine_types: ['Café', 'Western', 'Healthy'],
    cover_image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80',
    open_hours: 'Daily  7:30 AM – 9:00 PM',
    restaurant_ratings: [{ avg_rating: 4.4, review_count: 145 }],
    menu_url: null,
    menu_items: [
      { id: 'm61', category: 'Breakfast', name: 'Full English Breakfast', price: 1400, description: 'Eggs your way, bacon, toast, grilled tomato', is_available: true },
      { id: 'm62', category: 'Breakfast', name: 'Avocado Toast', price: 1100, description: 'Sourdough, smashed avocado, poached egg, chilli flakes', is_available: true },
      { id: 'm63', category: 'Breakfast', name: 'Smoothie Bowl', price: 900, description: 'Açaí base, granola, fresh fruit, honey', is_available: true },
      { id: 'm64', category: 'All Day', name: 'Grilled Cheese Sandwich', price: 750, description: 'Three-cheese blend on sourdough, tomato soup', is_available: true },
      { id: 'm65', category: 'All Day', name: 'Ella Burger', price: 1200, description: 'Beef patty, cheddar, caramelised onion, chips', is_available: true },
      { id: 'm66', category: 'Desserts', name: 'Banana Pancakes', price: 650, description: 'Fluffy pancakes, fresh banana, maple syrup', is_available: true },
      { id: 'm67', category: 'Coffee', name: 'Flat White', price: 380, description: 'Double shot espresso, microfoam milk', is_available: true },
      { id: 'm68', category: 'Coffee', name: 'Cold Brew', price: 420, description: '18-hour cold brewed coffee, served over ice', is_available: true },
    ],
  },
  {
    id: '8',
    name: 'Sunset Snack Bar',
    description: 'Popular evening snack spot. Famous for devilled cashews, pittu, hoppers and authentic string hopper platters.',
    town: 'Negombo',
    district: 'Gampaha',
    province: 'Western',
    address: '7 Lewis Place, Negombo',
    phone: '+94 31 223 4455',
    website: null,
    type: 'snack_bar',
    price_range: 'budget',
    cuisine_types: ['Snack Bar', 'Hoppers', 'Street Food'],
    cover_image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    open_hours: 'Daily  4:00 PM – 11:00 PM',
    restaurant_ratings: [{ avg_rating: 4.2, review_count: 56 }],
    menu_url: null,
    menu_items: [
      { id: 'm71', category: 'Hoppers', name: 'Plain Hopper', price: 35, description: 'Crispy bowl-shaped rice flour hopper', is_available: true },
      { id: 'm72', category: 'Hoppers', name: 'Egg Hopper', price: 55, description: 'Hopper with egg dropped in the centre', is_available: true },
      { id: 'm73', category: 'Hoppers', name: 'String Hoppers (6 pcs)', price: 120, description: 'Rice noodle nests served with dhal', is_available: true },
      { id: 'm74', category: 'Pittu', name: 'Red Rice Pittu', price: 90, description: 'Steamed red rice & coconut pittu with kiri hodi', is_available: true },
      { id: 'm75', category: 'Short Eats', name: 'Devilled Cashews', price: 200, description: 'Roasted cashews tossed in chilli and spices', is_available: true },
      { id: 'm76', category: 'Short Eats', name: 'Isso Vadai (3 pcs)', price: 180, description: 'Lentil fritter topped with whole prawn', is_available: true },
      { id: 'm77', category: 'Beverages', name: 'Ginger Beer', price: 100, description: 'Homemade spiced ginger beer', is_available: true },
    ],
  },
  {
    id: '9',
    name: 'Trinco Bay Hotel',
    description: 'Seaside hotel with an open-air restaurant offering fresh Eastern province seafood, crab and lobster dishes.',
    town: 'Trincomalee',
    district: 'Trincomalee',
    province: 'Eastern',
    address: 'Inner Harbour Road, Trincomalee',
    phone: '+94 26 222 1199',
    website: 'https://trincobayhotel.lk',
    type: 'hotel',
    price_range: 'mid',
    cuisine_types: ['Seafood', 'Sri Lankan', 'Hotel Buffet'],
    cover_image: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=600&q=80',
    open_hours: 'Daily  7:00 AM – 10:00 PM',
    restaurant_ratings: [{ avg_rating: 4.0, review_count: 72 }],
    menu_url: null,
    menu_items: [
      { id: 'm81', category: 'Breakfast', name: 'Sri Lankan Breakfast', price: 650, description: 'Hoppers, roti, egg, dhal, coconut sambol', is_available: true },
      { id: 'm82', category: 'Seafood', name: 'Lobster Thermidor', price: 4500, description: 'Half lobster in cream sauce, baked with cheese', is_available: true },
      { id: 'm83', category: 'Seafood', name: 'Trinco Crab Curry', price: 2800, description: 'Blue swimmer crab in Eastern-style coconut curry', is_available: true },
      { id: 'm84', category: 'Seafood', name: 'Grilled Tuna Steak', price: 2100, description: '200g yellowfin tuna, herb crust, citrus butter', is_available: true },
      { id: 'm85', category: 'Mains', name: 'Mutton Biryani', price: 1200, description: 'Fragrant mutton biryani with raita', is_available: true },
      { id: 'm86', category: 'Beverages', name: 'Thambili', price: 150, description: 'Fresh king coconut from local farms', is_available: true },
    ],
  },
  {
    id: '10',
    name: 'Kurunegala Street Bites',
    description: 'Casual lunch spot famous for lamprais, rice & curry parcels and freshly made short eats by the road.',
    town: 'Kurunegala',
    district: 'Kurunegala',
    province: 'North Western',
    address: '3 Clock Tower Road, Kurunegala',
    phone: '+94 37 222 6611',
    website: null,
    type: 'snack_bar',
    price_range: 'budget',
    cuisine_types: ['Street Food', 'Short Eats', 'Rice & Curry'],
    cover_image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
    open_hours: 'Mon – Fri  7:00 AM – 3:00 PM',
    restaurant_ratings: [{ avg_rating: 4.3, review_count: 48 }],
    menu_url: null,
    menu_items: [
      { id: 'm91', category: 'Rice & Curry', name: 'Lamprais', price: 280, description: 'Dutch-origin rice parcel baked in banana leaf', is_available: true },
      { id: 'm92', category: 'Rice & Curry', name: 'Rice Parcel (Leaf)', price: 200, description: 'Rice & curry wrapped in banana leaf', is_available: true },
      { id: 'm93', category: 'Short Eats', name: 'Bread Roll', price: 50, description: 'Deep-fried bread roll with spiced potato filling', is_available: true },
      { id: 'm94', category: 'Short Eats', name: 'Fish Bun', price: 60, description: 'Soft bun stuffed with spiced tuna', is_available: true },
      { id: 'm95', category: 'Short Eats', name: 'Coconut Toffee', price: 20, description: 'Traditional coconut and jaggery toffee', is_available: true },
      { id: 'm96', category: 'Beverages', name: 'Sweet Tea', price: 50, description: 'Ceylon tea with sugar', is_available: true },
    ],
  },
  {
    id: '11',
    name: 'Anuradhapura Rest House',
    description: 'Colonial-era rest house near the ancient city offering Sri Lankan meals and refreshments for visitors.',
    town: 'Anuradhapura',
    district: 'Anuradhapura',
    province: 'North Central',
    address: 'Maithripala Senanayake Mawatha, Anuradhapura',
    phone: '+94 25 222 2565',
    website: null,
    type: 'hotel',
    price_range: 'mid',
    cuisine_types: ['Sri Lankan', 'Rice & Curry', 'Buffet'],
    cover_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    open_hours: 'Daily  6:00 AM – 9:30 PM',
    restaurant_ratings: [{ avg_rating: 3.9, review_count: 34 }],
    menu_url: null,
    menu_items: [
      { id: 'ma1', category: 'Breakfast', name: 'Breakfast Set', price: 750, description: 'Egg, toast, cereal, tea or coffee, juice', is_available: true },
      { id: 'ma2', category: 'Lunch', name: 'Sri Lankan Lunch Buffet', price: 1500, description: '10-dish buffet, dessert and drinks included', is_available: true },
      { id: 'ma3', category: 'A La Carte', name: 'Chicken Curry & Rice', price: 680, description: 'Chicken curry with rice and side dishes', is_available: true },
      { id: 'ma4', category: 'A La Carte', name: 'Vegetable Fried Rice', price: 550, description: 'Egg fried rice with mixed vegetables', is_available: true },
      { id: 'ma5', category: 'Beverages', name: 'Ceylon Tea', price: 180, description: 'Premium Ceylon tea with milk', is_available: true },
    ],
  },
  {
    id: '12',
    name: 'Rathnapura Green Garden',
    description: 'Gem city favourite serving piping hot kola kenda, jackfruit curry, breadfruit dishes and herbal teas.',
    town: 'Ratnapura',
    district: 'Ratnapura',
    province: 'Sabaragamuwa',
    address: '55 Bandaranayake Mawatha, Ratnapura',
    phone: '+94 45 222 1033',
    website: null,
    type: 'restaurant',
    price_range: 'budget',
    cuisine_types: ['Sri Lankan', 'Herbal', 'Vegetarian'],
    cover_image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=80',
    open_hours: 'Mon – Sun  7:00 AM – 8:30 PM',
    restaurant_ratings: [{ avg_rating: 4.5, review_count: 67 }],
    menu_url: null,
    menu_items: [
      { id: 'mb1', category: 'Herbal Specials', name: 'Kola Kenda', price: 120, description: 'Traditional herbal rice porridge with seven herbs', is_available: true },
      { id: 'mb2', category: 'Herbal Specials', name: 'Herbal Tea Platter', price: 280, description: 'Assortment of 5 herbal teas with local honey', is_available: true },
      { id: 'mb3', category: 'Vegetarian Mains', name: 'Jackfruit Curry Plate', price: 320, description: 'Young jackfruit curry with rice and 3 sides', is_available: true },
      { id: 'mb4', category: 'Vegetarian Mains', name: 'Breadfruit Curry Plate', price: 300, description: 'Breadfruit curry with coconut milk', is_available: true },
      { id: 'mb5', category: 'Vegetarian Mains', name: 'Green Gram Curry', price: 280, description: 'Mung bean curry with red rice and pickle', is_available: true },
      { id: 'mb6', category: 'Sweets', name: 'Kiri Pani Bowl', price: 180, description: 'Buffalo curd with treacle and crushed kithul', is_available: true },
      { id: 'mb7', category: 'Sweets', name: 'Kavum & Kokis', price: 150, description: 'Traditional oil cake and crispy kokis', is_available: true },
    ],
  },
]

export const DUMMY_REVIEWS = [
  { id: 'r1', restaurant_id: '1', rating: 5, comment: 'Absolutely the best rice & curry in Galle! The fish ambulthiyal was outstanding.', created_at: '2026-04-10T08:32:00Z', profiles: { name: 'Nimal Perera', avatar_url: null } },
  { id: 'r2', restaurant_id: '1', rating: 5, comment: 'Generous portions, authentic flavours. Will definitely come back every visit.', created_at: '2026-03-22T14:15:00Z', profiles: { name: 'Ayasha Fernando', avatar_url: null } },
  { id: 'r3', restaurant_id: '1', rating: 4, comment: 'Very tasty food, slightly slow service on weekends but worth the wait.', created_at: '2026-02-14T11:00:00Z', profiles: { name: 'Rohan Silva', avatar_url: null } },
  { id: 'r4', restaurant_id: '2', rating: 5, comment: 'Stunning view and excellent fusion menu. The tuna tataki was a showstopper.', created_at: '2026-04-28T19:45:00Z', profiles: { name: 'Priya Dissanayake', avatar_url: null } },
  { id: 'r5', restaurant_id: '2', rating: 4, comment: 'Pricey but completely worth it for a special occasion. Cocktails are superb.', created_at: '2026-04-01T20:00:00Z', profiles: { name: 'Kasun Jayawardena', avatar_url: null } },
  { id: 'r6', restaurant_id: '3', rating: 4, comment: 'Love the croissants in the morning! Great spot to watch the lake while having breakfast.', created_at: '2026-03-05T07:50:00Z', profiles: { name: 'Sanduni Rathnayake', avatar_url: null } },
  { id: 'r7', restaurant_id: '5', rating: 5, comment: 'Freshest seafood I have ever had. The grilled prawns with garlic butter are divine!', created_at: '2026-05-02T13:20:00Z', profiles: { name: 'Mihail Ivanov', avatar_url: null } },
  { id: 'r8', restaurant_id: '6', rating: 5, comment: 'Authentic Jaffna taste. The crab curry is unlike anything in Colombo. Must visit!', created_at: '2026-04-18T12:00:00Z', profiles: { name: 'Kavitha Krishnamurthy', avatar_url: null } },
]

// Paginate helper
export function paginateDummy(items, page = 1, limit = 12) {
  const total      = items.length
  const totalPages = Math.ceil(total / limit)
  const start      = (page - 1) * limit
  const data       = items.slice(start, start + limit)
  return { data, total, totalPages, page }
}

// Filter helper — mirrors backend query params
export function filterRestaurants(params = {}) {
  let items = [...DUMMY_RESTAURANTS]
  const q = (params.q || '').toLowerCase()
  if (q) items = items.filter(r =>
    r.name.toLowerCase().includes(q) ||
    r.description.toLowerCase().includes(q) ||
    r.cuisine_types.some(c => c.toLowerCase().includes(q)) ||
    r.town.toLowerCase().includes(q)
  )
  if (params.province) items = items.filter(r => r.province === params.province)
  if (params.district) items = items.filter(r => r.district === params.district)
  if (params.town)     items = items.filter(r => r.town.toLowerCase().includes(params.town.toLowerCase()))
  if (params.type)     items = items.filter(r => r.type === params.type)
  if (params.price_range) items = items.filter(r => r.price_range === params.price_range)
  return paginateDummy(items, Number(params.page) || 1, Number(params.limit) || 12)
}
