export const THEMES = {
  warm: {
    label:       'Warm',
    description: 'Earthy orange — default',
    preview:     ['#e8702a', '#faf9f7', '#e8e4dc'],
    dark:        false,
    vars: {
      '--c-brand':    '#e8702a',
      '--c-brand-dk': '#c5501a',
      '--c-brand-lt': '#fff0e6',
      '--c-bg':       '#faf9f7',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f5f3ef',
      '--c-border':   '#e8e4dc',
      '--c-border2':  '#d4cfc5',
      '--c-text':     '#1c1a17',
      '--c-muted':    '#6b6660',
      '--c-dim':      '#9e9890',
    },
  },
  crimson: {
    label:       'Crimson',
    description: 'Bold red on clean white',
    preview:     ['#e11d48', '#ffffff', '#e8e8e8'],
    dark:        false,
    vars: {
      '--c-brand':    '#e11d48',
      '--c-brand-dk': '#be123c',
      '--c-brand-lt': '#fff1f2',
      '--c-bg':       '#ffffff',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f5f5f5',
      '--c-border':   '#e8e8e8',
      '--c-border2':  '#d4d4d4',
      '--c-text':     '#0a0a0a',
      '--c-muted':    '#737373',
      '--c-dim':      '#a3a3a3',
    },
  },
  ocean: {
    label:       'Ocean',
    description: 'Cool blue with sky tones',
    preview:     ['#0ea5e9', '#f0f9ff', '#bae6fd'],
    dark:        false,
    vars: {
      '--c-brand':    '#0ea5e9',
      '--c-brand-dk': '#0284c7',
      '--c-brand-lt': '#e0f2fe',
      '--c-bg':       '#f0f9ff',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#e0f2fe',
      '--c-border':   '#bae6fd',
      '--c-border2':  '#7dd3fc',
      '--c-text':     '#0c1a27',
      '--c-muted':    '#4a7a9b',
      '--c-dim':      '#7aabbf',
    },
  },
  forest: {
    label:       'Forest',
    description: 'Fresh green nature feel',
    preview:     ['#16a34a', '#f7fdf9', '#bbf7d0'],
    dark:        false,
    vars: {
      '--c-brand':    '#16a34a',
      '--c-brand-dk': '#15803d',
      '--c-brand-lt': '#f0fdf4',
      '--c-bg':       '#f7fdf9',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f0fdf4',
      '--c-border':   '#bbf7d0',
      '--c-border2':  '#86efac',
      '--c-text':     '#14261e',
      '--c-muted':    '#4d7a5e',
      '--c-dim':      '#86a891',
    },
  },
  violet: {
    label:       'Violet',
    description: 'Rich purple sophistication',
    preview:     ['#7c3aed', '#faf9ff', '#ddd6fe'],
    dark:        false,
    vars: {
      '--c-brand':    '#7c3aed',
      '--c-brand-dk': '#6d28d9',
      '--c-brand-lt': '#f5f3ff',
      '--c-bg':       '#faf9ff',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f5f3ff',
      '--c-border':   '#ddd6fe',
      '--c-border2':  '#c4b5fd',
      '--c-text':     '#1a1033',
      '--c-muted':    '#5b4d8a',
      '--c-dim':      '#8b7fad',
    },
  },
  midnight: {
    label:       'Midnight',
    description: 'Dark mode with indigo accent',
    preview:     ['#818cf8', '#0f0f14', '#2e2e3e'],
    dark:        true,
    vars: {
      '--c-brand':    '#818cf8',
      '--c-brand-dk': '#6366f1',
      '--c-brand-lt': '#1e1b4b',
      '--c-bg':       '#0f0f14',
      '--c-surface':  '#18181f',
      '--c-surface2': '#1f1f2a',
      '--c-border':   '#2e2e3e',
      '--c-border2':  '#3f3f55',
      '--c-text':     '#f4f4f8',
      '--c-muted':    '#9898b2',
      '--c-dim':      '#6b6b85',
    },
  },
}

export function buildThemeStyle(theme) {
  const vars = Object.entries(theme.vars).map(([k, v]) => `${k}:${v}`).join(';')
  return `:root{${vars}}`
}
