export const THEMES = {
  warm: {
    label:       'Warm',
    description: 'Earthy orange — default',
    preview:     ['#e8702a', '#faf9f7', '#e8e4dc'],
    dark:        false,
    vars: {
      '--c-brand':    '#e8702a',
      '--c-brand-dk': '#c5501a',
      '--c-brand-lt': '#fff0e6',
      '--c-bg':       '#faf9f7',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f5f3ef',
      '--c-border':   '#e8e4dc',
      '--c-border2':  '#d4cfc5',
      '--c-text':     '#1c1a17',
      '--c-muted':    '#6b6660',
      '--c-dim':      '#9e9890',
    },
  },
  crimson: {
    label:       'Crimson',
    description: 'Bold red on clean white',
    preview:     ['#e11d48', '#ffffff', '#e8e8e8'],
    dark:        false,
    vars: {
      '--c-brand':    '#e11d48',
      '--c-brand-dk': '#be123c',
      '--c-brand-lt': '#fff1f2',
      '--c-bg':       '#ffffff',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f5f5f5',
      '--c-border':   '#e8e8e8',
      '--c-border2':  '#d4d4d4',
      '--c-text':     '#0a0a0a',
      '--c-muted':    '#737373',
      '--c-dim':      '#a3a3a3',
    },
  },
  ocean: {
    label:       'Ocean',
    description: 'Cool blue with sky tones',
    preview:     ['#0ea5e9', '#f0f9ff', '#bae6fd'],
    dark:        false,
    vars: {
      '--c-brand':    '#0ea5e9',
      '--c-brand-dk': '#0284c7',
      '--c-brand-lt': '#e0f2fe',
      '--c-bg':       '#f0f9ff',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#e0f2fe',
      '--c-border':   '#bae6fd',
      '--c-border2':  '#7dd3fc',
      '--c-text':     '#0c1a27',
      '--c-muted':    '#4a7a9b',
      '--c-dim':      '#7aabbf',
    },
  },
  forest: {
    label:       'Forest',
    description: 'Fresh green nature feel',
    preview:     ['#16a34a', '#f7fdf9', '#bbf7d0'],
    dark:        false,
    vars: {
      '--c-brand':    '#16a34a',
      '--c-brand-dk': '#15803d',
      '--c-brand-lt': '#f0fdf4',
      '--c-bg':       '#f7fdf9',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f0fdf4',
      '--c-border':   '#bbf7d0',
      '--c-border2':  '#86efac',
      '--c-text':     '#14261e',
      '--c-muted':    '#4d7a5e',
      '--c-dim':      '#86a891',
    },
  },
  violet: {
    label:       'Violet',
    description: 'Rich purple sophistication',
    preview:     ['#7c3aed', '#faf9ff', '#ddd6fe'],
    dark:        false,
    vars: {
      '--c-brand':    '#7c3aed',
      '--c-brand-dk': '#6d28d9',
      '--c-brand-lt': '#f5f3ff',
      '--c-bg':       '#faf9ff',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f5f3ff',
      '--c-border':   '#ddd6fe',
      '--c-border2':  '#c4b5fd',
      '--c-text':     '#1a1033',
      '--c-muted':    '#5b4d8a',
      '--c-dim':      '#8b7fad',
    },
  },
  midnight: {
    label:       'Midnight',
    description: 'Dark mode with indigo accent',
    preview:     ['#818cf8', '#0f0f14', '#2e2e3e'],
    dark:        true,
    vars: {
      '--c-brand':    '#818cf8',
      '--c-brand-dk': '#6366f1',
      '--c-brand-lt': '#1e1b4b',
      '--c-bg':       '#0f0f14',
      '--c-surface':  '#18181f',
      '--c-surface2': '#1f1f2a',
      '--c-border':   '#2e2e3e',
      '--c-border2':  '#3f3f55',
      '--c-text':     '#f4f4f8',
      '--c-muted':    '#9898b2',
      '--c-dim':      '#6b6b85',
    },
  },
  sunset: {
    label:       'Sunset',
    description: 'Amber glow on deep mocha',
    preview:     ['#f59e0b', '#120d08', '#3d2d1a'],
    dark:        true,
    vars: {
      '--c-brand':    '#f59e0b',
      '--c-brand-dk': '#d97706',
      '--c-brand-lt': '#2d1e08',
      '--c-bg':       '#120d08',
      '--c-surface':  '#1c1410',
      '--c-surface2': '#271d12',
      '--c-border':   '#3d2d1a',
      '--c-border2':  '#54401f',
      '--c-text':     '#f5e6cc',
      '--c-muted':    '#a0845c',
      '--c-dim':      '#6b5535',
    },
  },
  rose: {
    label:       'Rose',
    description: 'Soft pink on cream white',
    preview:     ['#f43f5e', '#fff9fb', '#fecdd3'],
    dark:        false,
    vars: {
      '--c-brand':    '#f43f5e',
      '--c-brand-dk': '#e11d48',
      '--c-brand-lt': '#fff1f4',
      '--c-bg':       '#fff9fb',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#fff0f4',
      '--c-border':   '#fecdd3',
      '--c-border2':  '#fda4af',
      '--c-text':     '#1c0810',
      '--c-muted':    '#9f3055',
      '--c-dim':      '#c4748a',
    },
  },
  slate: {
    label:       'Slate',
    description: 'Clean steel minimal',
    preview:     ['#475569', '#f8fafc', '#e2e8f0'],
    dark:        false,
    vars: {
      '--c-brand':    '#475569',
      '--c-brand-dk': '#334155',
      '--c-brand-lt': '#f1f5f9',
      '--c-bg':       '#f8fafc',
      '--c-surface':  '#ffffff',
      '--c-surface2': '#f1f5f9',
      '--c-border':   '#e2e8f0',
      '--c-border2':  '#cbd5e1',
      '--c-text':     '#0f172a',
      '--c-muted':    '#64748b',
      '--c-dim':      '#94a3b8',
    },
  },
  carbon: {
    label:       'Carbon',
    description: 'Ultra dark with teal accent',
    preview:     ['#2dd4bf', '#060c0c', '#0d1f1f'],
    dark:        true,
    vars: {
      '--c-brand':    '#2dd4bf',
      '--c-brand-dk': '#14b8a6',
      '--c-brand-lt': '#042220',
      '--c-bg':       '#060c0c',
      '--c-surface':  '#0d1a1a',
      '--c-surface2': '#112020',
      '--c-border':   '#1a3030',
      '--c-border2':  '#234545',
      '--c-text':     '#e8fafa',
      '--c-muted':    '#7ab5b5',
      '--c-dim':      '#4a8585',
    },
  },
}

export function buildThemeStyle(theme) {
  const vars = Object.entries(theme.vars).map(([k, v]) => `${k}:${v}`).join(';')
  return `:root{${vars}}`
}

/**
 * Returns a plain-object snapshot safe for JSON.stringify / inline <script>.
 * Shape: { [key]: { vars: {...}, dark: boolean } }
 */
export function buildThemeSnapshot() {
  return Object.fromEntries(
    Object.entries(THEMES).map(([k, t]) => [k, { vars: t.vars, dark: t.dark }])
  )
}
